### ISSUE TITLE
Invalid Window Geometry 

### ISSUE THREAD

**Issue by QuantumCD** [rovsuite/monterey#21]
Recently when building Monterey, I started to notice errors while running the application regarding the window container geometry. The error message the application logs is always something like: 

```
setGeometry: Attempt to set a size (100x480) violating the constraints(100x100 - 98x16777215) on window 'QWindowContainerClassWindow'.
```

**Comment by QuantumCD** [comment]
I should also note that the application is not able to run with this error.

**Comment by QuantumCD** [comment]
Upon further inspection, if I leave the application as is (before the error started occuring), there is a similar error message regarding a Window container every time you resize the application. I'm assuming this probably has something to do with the QML components embedded in the main GUI.

**Comment by QuantumCD** [comment]
Wow, I really should have looked at this before filing an issue report. Sorry!

**Comment by chriskonstad** [comment]
Haha.  No worries!  Issue reports are really useful!
