### ISSUE TITLE
Empty Space in main GUI

### ISSUE THREAD

**Issue by QuantumCD** [rovsuite/monterey#24]
You said you are primarily concerned about UX at this point, so one suggestion I'd have is to do something with all this empty space near the depth counter. Now, I don't know if this is for something else, but I haven't been able to figure out what the purpose is. If the space is completely unused, perhaps you could extend the depth counter. That should be relatively easy, depending on how the depth counter works.

![image](https://f.cloud.github.com/assets/4673087/907517/97b3effe-fd43-11e2-99b6-28fca3c9a652.png)

**Comment by chriskonstad** [comment]
Here is the rough mockup of what I had in mind for Monterey's UI.  That blank space is going to be taken up by more graphs, and I want to add a compass band at the top of the video feed.  Kind of like this: http://www.blogcdn.com/wow.joystiq.com/media/2007/08/hud.jpg

If you have any better UI ideas, let me know!  I'm also thinking of changing out those LED widgets with some custom QML widgets that take up less space.  Or maybe subclassing QPushButton and making a special widget like these: https://sites.google.com/site/sf340com/DSC05478.JPG

![monterey mockup ui](https://f.cloud.github.com/assets/1539144/907565/f5efbcc0-fd47-11e2-8e8d-c4537d8080d4.png)

**Comment by QuantumCD** [comment]
Hmm. The buttons wouldn't be too hard to do if you had the right images. They'd be really easy if you used QML. As for the HUD you linked to... that'd be considerably harder. You would have to get constant data from a monitor or something and update that. To me, that would be the hard part--linking the two. That's not really my area of expertise though. 

Also, the general idea of the HUD looks pretty cool and easy to use. Although in terms of UX, I think the uptime and current time should be closer together.

**Comment by chriskonstad** [comment]
Don't worry about the data part, I've got that covered. I just need help making the widget and getting the UI all setup. There is a model of the ROV, which is the QROV class. That holds all sensor values and the UI is updated on a timer.

**Comment by QuantumCD** [comment]
Oh, okay. Hmm, to start, we'll need the images. We might be able to use a font and somehow cut down on the number of images for the QML. It might not be worth if though, if you are just going to be using a few buttons.

As for the airplane-like HUD... well, that might be something for a more advanced API, such as OpenGL.

**Comment by chriskonstad** [comment]
Oh okay.  I guess we can just use stylesheets on a subclass of QPushButton that ignores click events (for replacing the LEDs).  Do you know OpenGL?  If not, I think that a QML window with a transparent background placed over the video display should work, right?

**Comment by QuantumCD** [comment]
Well, the more I think about it, the QML would most likely work. You could just use layouts/positioners for the lines, and have them all rotate at once pretty easily. I wonder how we could get a green glow effect though, which would look cool for the lines. Perhaps a rectangle with a lower opacity, as well as a gradient that is just a few pixels wider than the line on both sides.

**Comment by chriskonstad** [comment]
Okay.  Yeah, that should work.  The glow effect would be easy in Photoshop, although we don't really need it.  What I would do to make it is create a feathered rectangle with green as the main color and transparent as the background color that the main color is blended with.  Then take that image and put it behind any green lines on the HUD and it will give it a glow effect.  That being said, I don't know if we need a glow effect.

**Comment by QuantumCD** [comment]
You are definitely right about the necessity of the glow effect, but it would still be a cool touch if the lines look bland. For the LED indicators, we could definitely go all out with QML. As for the image, we could use something like this with different colors (sans the power button in the middle :P). http://rgbjam.com/tutorials/create-an-onoff-button-in-photoshop A blinking state would be interesting too ;). Also, I think the time it would take to sub-class QPushButton and get a really polished result just isn't worth it--especially since Digia and the Qt developers are really pushing QML now. (I think the Widgets module was even labelled as "finished"). 

Do you think it'd be better to make a QML scene, or several smaller buttons grouped together in a Widgets form layout? Performance-wise, I'm wondering if one QML scene would be better and have less overhead, but the alternative seems to be more flexible. I suppose we could always separate the button into its own QML file and use it as a component in other QML files. That would be good enough in terms of extensibility goes, I think.

**Comment by chriskonstad** [comment]
Very true!  Yeah, I think that QML would be a better way than subclassing QPushButton for handling status indicators.  My thought is that the status indicators could look kinda like the status lights in the upper left of this UI. http://api.ning.com/files/It3-odgnrfSOdXjDnGPiYm7*UonrKrfZN*Ey1c7Uk13GX89fs*LK4o50pQfqKMy9xAIj0XRYAlhSZxNP3An0JAJYCP2HZ1eg/mockup1b.png?width=750

Not exactly like those, but a similar (i.e. flat) look.  What do you think about that?  I'm not sure about performance, but I think the best place to start would be to make each indicator its own component.  By doing that, we can either do one scene or several scenes. An added benefit of using one scene is that the background between the indicators would be a single color of our choice, as opposed to the default palette value.

**Comment by QuantumCD** [comment]
Wow, those are really cool! What would the font for those be though, you think? Other than that, I think those would be relatively easy to prototype with QML. I'll start on a first iteration and post some images, but I'll need the font. I don't know how QML handles fonts that aren't installed or built-in though.

**Comment by chriskonstad** [comment]
Yeah!  And they'd be pretty easy to make.  I don't really want to replicate them perfectly because that's the UI sketch idea for OpenROV's control system, but that style of button is what I had in mind.  That being said, I've spent some time looking for that font and I can't find it anywhere.  I can find font similar to that, but it always has a slight issue with it (numbers looking weird, etc).  Is it possible to package fonts in the Qt resource files (QRC)?

**Comment by QuantumCD** [comment]
Apparently there is a FontLoader element! I never knew, but good to know about. It is able to load from a URL, so I'm assuming we could use QRC for the TTF. As for the font, I came up with nothing either.

**Comment by QuantumCD** [comment]
I just wrote a quick blog post about the element: http://contingencycoder.wordpress.com/2013/08/05/quick-tip-load-fonts-from-a-local-file-with-qml/

**Comment by chriskonstad** [comment]
Oh nice!  That's good to know about!  I'm glad it's so easy to bundle fonts with an application!

**Comment by chriskonstad** [comment]
I've taken a theme from https://github.com/dasanchez/flipp and tweaked it a little for Monterey.  Tell me what you think!  I'm still not done with it, but I think it's coming along nicely.
![mainwindow](https://f.cloud.github.com/assets/1539144/960453/edb011dc-04b7-11e3-8a94-2c350ff35d07.PNG)
![settings](https://f.cloud.github.com/assets/1539144/960456/f16c720c-04b7-11e3-92e3-a974d5bc513e.PNG)
![joystick](https://f.cloud.github.com/assets/1539144/960457/f4519ba0-04b7-11e3-844e-ba5672287180.PNG)
![debug](https://f.cloud.github.com/assets/1539144/960460/018391fc-04b8-11e3-9643-c7e1f793198c.PNG)
![about](https://f.cloud.github.com/assets/1539144/960461/035ad666-04b8-11e3-9df0-1e493f2519de.PNG)

**Comment by QuantumCD** [comment]
Oh, that reminds me, a theme! I wrote a dark version of the Fusion theme, which has a complete dark palette (I think) and a nice tool tip style sheet to go along with it. Rather, I used a palette and a stylesheet or two--it is still the Fusion theme. I'll post it on my blog when I get everything on my PC set back up. Recently went through a pretty hard crash, but luckily all my useful code was in a remote somewhere. :) I'm more worried about setting my development environment back up... all of it :| If I'm lucky, I'll be building again by tomorrow though!

**Comment by chriskonstad** [comment]
Oh nice!  Maybe we could use that for Monterey?  The current theme works, but it has a few graphical glitches that I can't seem to fix.  (See the clipping of the corners of the border around the QTextEdit on the "About" window.  Yikes.  Crashes are never fun, but I'm glad your code was backed up!  If you need any help setting up your dev environment for Monterey, let me know.  After all, the goal is to make it easy for everyone to download the source and start tweaking it.

**Comment by QuantumCD** [comment]
I posted the theme on Github and my blog. Feel free to try it out/tweak it while I continue setting up my environment. 
Here's the Gist: https://gist.github.com/QuantumCD/6245215#file-qt-5-dark-fusion-palette

**Comment by QuantumCD** [comment]
I see you seemed to have changed the theme. Could I get a screenshot? I'm still working on Visual Studio and the Windows SDK, but I might have Qt in a day or two.

**Comment by chriskonstad** [comment]
I just wrote a blog entry with a screen shot.  Any thoughts?  I might change the buttona and slider handles to either be lighter or bluer so that they stand out more against that dark background, but I'm not sure yet.

http://chrisstechblog.blogspot.com/2013/08/monterey-30-status-report.html

**Comment by QuantumCD** [comment]
Very nice! And the status handles wouldn't be too hard to change, I do not think. I'll definitely look into that when I get my development environment working. I finally got Visual Studio and the Windows SDK installed (I think I got everything) and tomorrow it's Qt :) Also, are you going to work on the LED indicators or would you like me to? I could probably get something started with a concept of the buttons you posted a while ago (http://api.ning.com/files/It3-odgnrfSOdXjDnGPiYm7*UonrKrfZN*Ey1c7Uk13GX89fs*LK4o50pQfqKMy9xAIj0XRYAlhSZxNP3An0JAJYCP2HZ1eg/mockup1b.png?width=750) Did you ever find a font?

**Comment by chriskonstad** [comment]
Yup!  I think it looks great!  Okay. I'm glad to hear that your system is coming back together well.  If you want to work on the indicators, that'd be great.  I think the best way of doing that now would be to make a general indicator QML file (in which you can set the name and state) so that way we can easily add more indicators later.  We can use the layout of the status light groupbox to layout multiple QQuickViews.  How does that sound?  And no, I never found the font.

**Comment by QuantumCD** [comment]
Okay, got my Qt environment setup, finally! Here's what I have so far for the LED Indicators. https://dl.dropboxusercontent.com/u/75795798/Code/LEDIndicatorTest.zip I tested them out with some positioners as well, and they seemed to work pretty well! I also added a bit of a transition when you change the state to "On" to catch your eye. When they are off, they sort of fade into the background so you can easily tell which are on/off at a glance. I kept the font at Arial for now, but you could easily change that in the future I'm guessing. Any suggestions?

**Comment by chriskonstad** [comment]
Looks awesome!  I love it!  Those transitions really give it a nice effect.  I like the look of Arial for the time being, as most of the more Sci-fy fonts have weird looking numbers or are too hard to read.  I guess we could look for some FOSS font websites.  Arial doesn't look bad, it just is kinda plain.

**Comment by chriskonstad** [comment]
How do you want to add the new status indicators to Monterey?  Do you want me to add them for you or do you want to do that?

**Comment by QuantumCD** [comment]
You should probably add them, as I haven't really looked into how you are hooking them into your back-end. I should really look over Monterey's codebase when I get some time. :P 

Basically, I have a property for the LEDIndicator component that controls the state. It's just a boolean, so it shouldn't be too hard to change it in C++. Then you have the title indicator, of course, which can probably be setup in the QML file or through C++. The state change should happen automatically when you change the "isOn" boolean property or whatever I called it. If you looked at the code, it's pretty obvious. Feel free to change anything (I didn't know how big to make them at the time).

**Comment by chriskonstad** [comment]
Okay. I'll do that!  If you want, you can add the QML files to the repo so that it's in the git log that you contributed them.  Then, I can plug them in to Monterey.  Otherwise, I can just add the files you sent me and add them to Monterey.  Haha.  The UI code is all in the classes with UI files along with the DepthTape and Compass classes that represent QML "widgets".

Yeah.  I learned recently how to change properties in QML from C++, so it should be easy to set everything up.  Thanks for the awesome code, by the way!

**Comment by QuantumCD** [comment]
Okay, I added the QML code. Feel free to try out the indicators in a layout, and assign any bugs to me! Haha.

**Comment by chriskonstad** [comment]
Okay.  Will do. Thanks for the help!  And don't worry, any bugs I find will be sent your way. ;)

**Comment by QuantumCD** [comment]
Hmm, unfortunately, changing the width of the slider handles doesn't seem to work for some reason. It could be the Fusion theme. I might try sub-classing a QSlider and expand the sliders if that wouldn't turn out extremely complex. That could cause issues with the theme though.

**Comment by chriskonstad** [comment]
Oh!  I'm less worried about the width and more worried about the color scheme.  I don't think they have enough contrast with the background.  What do you think?

**Comment by QuantumCD** [comment]
Oh, that's a good point. Hmm, I'll try a style sheet then, and if that doesn't work, maybe there is some super-secret palette somewhere that controls the handle's color. :P

**Comment by chriskonstad** [comment]
Haha.  Okay.  I tried editing the palette that is applied to the whole app (I changed the Button field to the blue color), and that worked.  It had some unintended consequences with other widgets, but it would be super easy to apply it only to QPushButtons and QSliders.  Just do a foreach loop to iterate through all widgets in MainWindow and if they are either a QPushButton or a QSlider, then set the QPalette::Button to the blue color (qApp->palette()->highlight()).  That, I think, should do the trick.

**Comment by chriskonstad** [comment]
Also, side question: would you like me to publicize your rovsuite organization member status on Github?  That means that when people go to github.com/rovsuite and click on the list of members, you'll show up too.  If you don't, no worries.
