### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by chriskonstad** [rovsuite/monterey#48]
The downloaded zip archive for Monterey 3.0 for Windows crashes on some systems but not others.  It works fine on mine, but it crashes on another on of my Windows 7x64 machines and the machine of another (both 32 and 64bit).

Hey QuantumCD, any thoughts?  I assigned you to this to alert you to this crash, but you don't need to be the person to fix it.  I just wanted to see if you had any ideas.

**Comment by QuantumCD** [comment]
I'm going to try running it and see if I get a crash. Since I have the environment for Qt applications, perhaps we can see if it's just for people who do not have adequate Qt environments.

**Comment by QuantumCD** [comment]
Yeah, I'm getting the error. Odd.

**Comment by QuantumCD** [comment]
Running Monterey through Dependency Walker shows me this:
![image](https://f.cloud.github.com/assets/4673087/1046148/97825996-1033-11e3-8d89-a9f326d228b1.png)
Notice the various DLL's that weren't found. I don't know if this is the problem, but it could be.

**Comment by chriskonstad** [comment]
When I change my Qt directory, I get the same crash on my dev machine.  It looks like it is trying to load something within the Qt directory.

**Comment by QuantumCD** [comment]
Those are really interesting not-found errors, considering they seem to be dependencies of USER32.DLL

**Comment by chriskonstad** [comment]
Those are interesting errors. Can you post a screenshot of your Qt5Core.dll checksums?

**Comment by QuantumCD** [comment]
I was just about to do that. :P
![image](https://f.cloud.github.com/assets/4673087/1046176/719ae7ce-1034-11e3-835b-c6cdb112a751.png)

**Comment by QuantumCD** [comment]
Those are very slight differences in the checksum. Really odd. I wonder if this is a bug with Qt itself and how they built Qt Core?

**Comment by QuantumCD** [comment]
I'm pretty sure that checksums should be the same. Dependency Walker also says this in its documentation, briefly: 
![image](https://f.cloud.github.com/assets/4673087/1046212/362a7528-1035-11e3-8e28-97d3fe702098.png)

**Comment by QuantumCD** [comment]
Okay, that's really weird. If I put Monterey and SDL right in the MinGW bin directory, it runs just fine. That limits it down to either a missing or corrupted DLL, I think.

**Comment by QuantumCD** [comment]
I've confirmed it's a corrupted QtCore.dll. Copying over a clean QtCore.dll resolves the problem.

**Comment by QuantumCD** [comment]
I'm publishing a new release for the fix.

**Comment by QuantumCD** [comment]
Just drafted. See if it works for you.

**Comment by chriskonstad** [comment]
Hmm... I'm getting a 404 when I try to download it

**Comment by chriskonstad** [comment]
Also, where did you get the other Qt5Core.dll?

**Comment by chriskonstad** [comment]
I'm still getting a 404 on that download link.  Maybe you could email or Dropbox me a copy of it?

**Comment by QuantumCD** [comment]
I'm getting a 404 too. That's weird.

**Comment by QuantumCD** [comment]
Sorry, I was helping out someone else. I'll Dropbox is right quick.

**Comment by QuantumCD** [comment]
Also, perhaps we should get some sort of IRC for Monterey or something going? I think we post comments way too much on Github and your blog.

**Comment by QuantumCD** [comment]
Here's the DB Link for now. https://www.dropbox.com/s/qrhbdla6iqijopt/Monterey-3-0-Win32.zip See if you can download that.

**Comment by chriskonstad** [comment]
Okay. Sounds good! I like that IRC idea. I had originally thought of having a wiki and a forum because my goal is to create an ROV control system that people can modify and add features to themselves (like extra sensors, etc). What would the best communication setup for ROV-Suite be? I do agree that we need a better method than comments on blogs and issues. An IRC channel would be nice.

**Comment by QuantumCD** [comment]
We could look at freenode.net maybe? I know it's for FOSS projects like Monterey. We could also use a Wikia maybe. Those have a chat built-in. It would probably be better, as people could create wiki pages and stuff detailing different things. It's really just a step up from Github's wiki with a chat.

**Comment by chriskonstad** [comment]
Those are interesting ideas! We should take a look at those sooner rather than later.

**Comment by chriskonstad** [comment]
And I'll have to check out that download link in a little bit. I'm not at my computer at the moment.

**Comment by QuantumCD** [comment]
Yeah, I'm not too familiar with IRC (creating/managing) but I have used Wikia before (still didn't create it). Wikia has a lot of ads and a lot of spammers that just like to ruin your work. However, it's free and you do get a chat and some other nice features. IRC would probably be better for just developers to talk, but a Wikia would definitely be the way to go if you think we should get something like forums/tutorials and stuff up.

**Comment by QuantumCD** [comment]
Yeah, I'm not too familiar with IRC (creating/managing) but I have used Wikia before (still didn't create it). Wikia has a lot of ads and a lot of spammers that just like to ruin your work. However, it's free and you do get a chat and some other nice features. IRC would probably be better for just developers to talk, but a Wikia would definitely be the way to go if you think we should get something like forums/tutorials and stuff up.

**Comment by QuantumCD** [comment]
I don't know what happened there, that was weird (double post), but definitely try out the download later. I got the DLL from my bin directory after verifying the checksums. I'll send it to you so you can hopefully replace your corrupted DLL in release builds from now until it's fixed with Qt. 

Here's the link to the Qt5Core.dll that seemed to work: https://www.dropbox.com/s/knima17e9q1bmpy/Qt5Core.dll

**Comment by chriskonstad** [comment]
Okay. I'll try it out. Could we host the wiki at Github? Maybe do IRC and a wiki on Github?

**Comment by QuantumCD** [comment]
Yeah, definitely. I'll look into creating the IRC server. I could always write our own Qt chat client.... it has been a while since I posted some tutorials on my blog.... ;) 

No, in all seriousness, I'll look into freenode. I think Qt and KDE use it as well, so it has to have some sort of familiarity with developers.

**Comment by QuantumCD** [comment]
Hmm... the more I think about it, a Wikia might be better. It would definitely be a lot easier for other people to edit.

**Comment by QuantumCD** [comment]
I'll still try and set us up an IRC chat on freenode though, in the meantime.

**Comment by QuantumCD** [comment]
Okay, I registered #Monterey on Freenode. Feel free to join sometime and I will op you.

**Comment by chriskonstad** [comment]
That'd be pretty cool!  Although deploying it might be troublesome.... ;)  Okay.  So we can do Wikia for a wiki and then IRC for chatting?  That works for me!  Sorry about not being on tonight.  I had to go to dinner with relatives.  I'm not sure which timezone you're in, but I'll be on tomorrow evening PST.

**Comment by chriskonstad** [comment]
Oh, and I couldn't get your Dropbox link to run... :(  Which compiler did you use?

**Comment by QuantumCD** [comment]
This Dropbox link? https://dl.dropboxusercontent.com/s/qrhbdla6iqijopt/Monterey-3-0-Win32.zip?&dl=1 That should work. It's the Monterey 3.0 .zip with a replaced Qt5Core.dll that seems to be in working order.

**Comment by QuantumCD** [comment]
I made a wiki here: http://monterey.wikia.com/wiki/Monterey_Wiki I'll start work on it. My username on Wikia is "TheMachine.Wiki" (from an old video game)

**Comment by QuantumCD** [comment]
I'll be on the Wiki chat later. Be sure to make an account and I'll add you as an administrator when I catch you. For now I just updated the home page and messages, and also created the forum.

**Comment by chriskonstad** [comment]
I still get the Windows Visual C++ Runtime Library crash dialog box.  Windows Event log says that the "Faulting Module Name" was Qt5Core.dll. 

Nice! I'll get on the Wikia as soon as they send my confirmation email.  And I'm on the IRC right now.  I'll have to leave it soon for a little bit, but I"ll try to be on IRC as much as I can be today.

**Comment by chriskonstad** [comment]
Taken care of! See my blog for details. Also, the zip archive is in the release page.
