### ISSUE TITLE
Monterey video display showing a question mark instead of video (Windows)

### ISSUE THREAD

**Issue by chriskonstad** [rovsuite/monterey#54]
Monterey depends on the image plugins to show the video feed, which I didn't realize were necessary for it to work... My bad!  I'll take care of this as soon as I get access to my windows computer.

Thank you to the user who emailed me the bug report!

**Comment by QuantumCD** [comment]
Which image plugins are missing?

**Comment by chriskonstad** [comment]
I think it's the jpeg plugin.  You can find it in in QTDIR/5.1.0/mingw/plugins (I think...).  It might be safe to include all of the image plugins (there aren't that many) just incase someone points that video viewer to a webpage that includes images of other types (i.e. maybe they rolled their own bottomside and want to have a mini-UI appear there).

**Comment by QuantumCD** [comment]
That sounds like a good idea. I have the DLLs for MinGW 4.8 32 bit builds on my screen right now. Did you want them?

**Comment by chriskonstad** [comment]
I've taken care of it now.
