### ISSUE TITLE
Can only work with Qt 5.1 and Qt 5.1.1.

### ISSUE THREAD

**Issue by chriskonstad** [rovsuite/monterey#58]

**Comment by QuantumCD** [comment]
What kind of issues are preventing Monterey from running in 5.2/5.3?

**Comment by chriskonstad** [comment]
There was a bug emailed to me with an error that I've never seen in Qt 5.1.1.
Starting E:\monterey\build-Monterey-Desktop_Qt_5_2_1_MinGW_32bit-Release\release\Monterey.exe...
QSslSocket: cannot resolve TLSv1_1_client_method
QSslSocket: cannot resolve TLSv1_2_client_method
QSslSocket: cannot resolve TLSv1_1_server_method
QSslSocket: cannot resolve TLSv1_2_server_method
QMetaObject::connectSlotsByName: No matching signal for on_pbRelay_clicked()
No joystick attached!
Controller finished setup!
create: CreateWindowEx failed (Cannot create a top-level child window.)
E:\monterey\build-Monterey-Desktop_Qt_5_2_1_MinGW_32bit-Release\release\Monterey.exe exited with code 3

Also, I had compilation problems last time I tried to use a newer Qt version on OSX.  But I just tried to use Qt 5.2.1 (OSX) and it worked, so I'm not sure what's going on.

**Comment by QuantumCD** [comment]
SSL errors... ugh. I had some issues with a little project of mine that was built on Qt 5.2. I think the libSSL or whatever stopped shipping with Qt, so you have to build/download binaries of that separately now. Perhaps try that?

**Comment by chriskonstad** [comment]
Fixed.  

d7ac9ec17407f31515b4fb0d068be4762f58d5e9
